### ISSUE TITLE
Replace `saleUnitId` with `merchantSerialNumber`

### ISSUE THREAD

**Issue by cloveras** [vippsas/vipps-psp-api#33]
See the RFC: https://github.com/vippsas/vipps-rfc/blob/master/0001-api-guidelines.md#common-data-types-and-examples

**Comment by tht13** [comment]
please link these to lines in the code where they are wrong

**Comment by cloveras** [comment]
Hmmm. I'm actually not sure what's right here, so this should be made clearer:

```
    merchantId:
      name: merchantId
      schema:
        type: string
      in: path
      required: true
      description: The Vipps merchant serial number
 saleUnitId:
      name: saleUnitId
      schema:
        type: string
      in: path
      required: true
      description: The Vipps saleunit serial number
```
